In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv(r"E:\Pós\data\nycflights.csv")

In [4]:
df

,Unnamed: 0,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,1,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,3,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,4,2013,1,1,544.0,-1.0,1004.0,-18.0,B6,N804JB,725,JFK,BQN,183.0,1576,5.0,44.0
4,5,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336772,2013,9,30,NaN,NaN,NaN,NaN,9E,NaN,3393,JFK,DCA,NaN,213,NaN,NaN
336772,336773,2013,9,30,NaN,NaN,NaN,NaN,9E,NaN,3525,LGA,SYR,NaN,198,NaN,NaN
336773,336774,2013,9,30,NaN,NaN,NaN,NaN,MQ,N535MQ,3461,LGA,BNA,NaN,764,NaN,NaN
336774,336775,2013,9,30,NaN,NaN,NaN,NaN,MQ,N511MQ,3572,LGA,CLE,NaN,419,NaN,NaN
336775,336776,2013,9,30,NaN,NaN,NaN,NaN,MQ,N839MQ,3531,LGA,RDU,NaN,431,NaN,NaN

In [5]:
df = df.drop(columns=['Unnamed: 0'])

In [6]:
df

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,544.0,-1.0,1004.0,-18.0,B6,N804JB,725,JFK,BQN,183.0,1576,5.0,44.0
4,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,NaN,NaN,NaN,9E,NaN,3393,JFK,DCA,NaN,213,NaN,NaN
336772,2013,9,30,NaN,NaN,NaN,NaN,9E,NaN,3525,LGA,SYR,NaN,198,NaN,NaN
336773,2013,9,30,NaN,NaN,NaN,NaN,MQ,N535MQ,3461,LGA,BNA,NaN,764,NaN,NaN
336774,2013,9,30,NaN,NaN,NaN,NaN,MQ,N511MQ,3572,LGA,CLE,NaN,419,NaN,NaN
336775,2013,9,30,NaN,NaN,NaN,NaN,MQ,N839MQ,3531,LGA,RDU,NaN,431,NaN,NaN

In [7]:
#tirando todos os voos cancelados, pois analisaremos atrasos
df = df.dropna(subset=["dep_time", "arr_time"])

In [8]:
#formatando dep_time em HH:MM
df = df.copy()

# Converter para string com zeros à esquerda
df["dep_time"] = df["dep_time"].astype(pd.Int64Dtype()).astype(str).str.zfill(4)

# Converter para datetime e formatar como HH:MM
df["dep_time"] = pd.to_datetime(
    df["dep_time"], 
    format="%H%M", 
    errors="coerce"
).dt.strftime("%H:%M")

df

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,05:17,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,05:33,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,05:42,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,05:44,-1.0,1004.0,-18.0,B6,N804JB,725,JFK,BQN,183.0,1576,5.0,44.0
4,2013,1,1,05:54,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336765,2013,9,30,22:40,-5.0,2334.0,-17.0,B6,N354JB,1816,JFK,SYR,41.0,209,22.0,40.0
336766,2013,9,30,22:40,-10.0,2347.0,-20.0,B6,N281JB,2002,JFK,BUF,52.0,301,22.0,40.0
336767,2013,9,30,22:41,-5.0,2345.0,-16.0,B6,N346JB,486,JFK,ROC,47.0,264,22.0,41.0
336768,2013,9,30,23:07,12.0,2359.0,1.0,B6,N565JB,718,JFK,BOS,33.0,187,23.0,7.0
336769,2013,9,30,23:49,-10.0,325.0,-25.0,B6,N516JB,745,JFK,PSE,196.0,1617,23.0,49.0

In [9]:
df = df.copy()

# Converter para string com zeros à esquerda
df["air_time"] = df["air_time"].astype(pd.Int64Dtype()).astype(str).str.zfill(4)

# Converter para datetime e formatar como HH:MM
df["air_time"] = pd.to_datetime(
    df["air_time"], 
    format="%H%M", 
    errors="coerce"
).dt.strftime("%H:%M")
    
df

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,05:17,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,02:27,1400,5.0,17.0
1,2013,1,1,05:33,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,02:27,1416,5.0,33.0
2,2013,1,1,05:42,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,NaN,1089,5.0,42.0
3,2013,1,1,05:44,-1.0,1004.0,-18.0,B6,N804JB,725,JFK,BQN,NaN,1576,5.0,44.0
4,2013,1,1,05:54,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,01:16,762,5.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336765,2013,9,30,22:40,-5.0,2334.0,-17.0,B6,N354JB,1816,JFK,SYR,00:41,209,22.0,40.0
336766,2013,9,30,22:40,-10.0,2347.0,-20.0,B6,N281JB,2002,JFK,BUF,00:52,301,22.0,40.0
336767,2013,9,30,22:41,-5.0,2345.0,-16.0,B6,N346JB,486,JFK,ROC,00:47,264,22.0,41.0
336768,2013,9,30,23:07,12.0,2359.0,1.0,B6,N565JB,718,JFK,BOS,00:33,187,23.0,7.0
336769,2013,9,30,23:49,-10.0,325.0,-25.0,B6,N516JB,745,JFK,PSE,NaN,1617,23.0,49.0

In [10]:
df.isnull().sum()

year             0
month            0
day              0
dep_time        29
dep_delay        0
arr_time         0
arr_delay      717
carrier          0
tailnum          0
flight           0
origin           0
dest             0
air_time     98420
distance         0
hour             0
minute           0
dtype: int64

In [11]:
df[df["arr_delay"].isnull()]

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
471,2013,1,1,15:25,-5.0,1934.0,NaN,MQ,N719MQ,4525,LGA,XNA,NaN,1147,15.0,25.0
477,2013,1,1,15:28,29.0,2002.0,NaN,EV,N17108,3806,EWR,STL,NaN,872,15.0,28.0
615,2013,1,1,17:40,-5.0,2158.0,NaN,MQ,N739MQ,4413,LGA,XNA,NaN,1147,17.0,40.0
643,2013,1,1,18:07,29.0,2251.0,NaN,UA,N31412,1228,EWR,SAN,NaN,2425,18.0,7.0
725,2013,1,1,19:39,59.0,29.0,NaN,9E,N905XJ,3325,JFK,DFW,NaN,1391,19.0,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334197,2013,9,28,05:55,-5.0,953.0,NaN,EV,N133EV,5068,EWR,DTW,NaN,488,5.0,55.0
334354,2013,9,28,08:47,8.0,1130.0,NaN,EV,N14542,4510,EWR,MKE,NaN,725,8.0,47.0
334412,2013,9,28,10:10,-10.0,1344.0,NaN,EV,N12175,4412,EWR,DSM,NaN,1017,10.0,10.0
334495,2013,9,28,12:14,-11.0,1801.0,NaN,AA,N488AA,300,EWR,DFW,NaN,1372,12.0,14.0
335534,2013,9,29,17:34,23.0,2159.0,NaN,UA,N463UA,327,EWR,PDX,NaN,2434,17.0,34.0

In [12]:
df_clean = df.dropna()

In [13]:
df_clean.isnull().sum()

year         0
month        0
day          0
dep_time     0
dep_delay    0
arr_time     0
arr_delay    0
carrier      0
tailnum      0
flight       0
origin       0
dest         0
air_time     0
distance     0
hour         0
minute       0
dtype: int64

In [14]:
df_clean

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,05:17,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,02:27,1400,5.0,17.0
1,2013,1,1,05:33,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,02:27,1416,5.0,33.0
4,2013,1,1,05:54,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,01:16,762,5.0,54.0
5,2013,1,1,05:54,-4.0,740.0,12.0,UA,N39463,1696,EWR,ORD,01:50,719,5.0,54.0
6,2013,1,1,05:55,-5.0,913.0,19.0,B6,N516JB,507,EWR,FLL,01:58,1065,5.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336764,2013,9,30,22:37,-8.0,2345.0,-8.0,B6,N318JB,234,JFK,BTV,00:43,266,22.0,37.0
336765,2013,9,30,22:40,-5.0,2334.0,-17.0,B6,N354JB,1816,JFK,SYR,00:41,209,22.0,40.0
336766,2013,9,30,22:40,-10.0,2347.0,-20.0,B6,N281JB,2002,JFK,BUF,00:52,301,22.0,40.0
336767,2013,9,30,22:41,-5.0,2345.0,-16.0,B6,N346JB,486,JFK,ROC,00:47,264,22.0,41.0
336768,2013,9,30,23:07,12.0,2359.0,1.0,B6,N565JB,718,JFK,BOS,00:33,187,23.0,7.0

In [15]:
df_clean.groupby('carrier')['arr_delay'].mean()

carrier
9E     7.074199
AA    -0.021670
AS    -9.885542
B6     8.418858
DL     1.235931
EV    15.809106
F9    20.812596
FL    19.365264
HA    -6.324138
MQ    12.637833
OO    20.000000
UA     3.245162
US     3.402520
VX    -0.376756
WN     9.721189
YV    18.410959
Name: arr_delay, dtype: float64

In [16]:
df_clean['arr_delay'].mean()

np.float64(6.3746276586479)

In [17]:
df_clean['carrier'].value_counts()

carrier
UA    44338
B6    42592
DL    34917
EV    32154
AA    24319
MQ    11202
9E    10674
WN    10534
US    10397
VX     4199
FL     2401
AS      664
F9      651
YV      292
HA      290
OO        4
Name: count, dtype: int64

In [18]:
df_clean[df_clean['arr_delay'] > 0].groupby('carrier').size()

carrier
9E     4061
AA     7857
AS      167
B6    17588
DL    11706
EV    15498
F9      366
FL     1470
HA       79
MQ     5491
OO        2
UA    16717
US     4115
VX     1278
WN     4713
YV      166
dtype: int64

In [19]:
total_voos = df_clean['carrier'].value_counts()
total_atrasos = df_clean[df_clean['arr_delay'] > 0]['carrier'].value_counts()

proporcao = (total_atrasos / total_voos).sort_values(ascending=False)
print(proporcao)

carrier
FL    0.612245
YV    0.568493
F9    0.562212
OO    0.500000
MQ    0.490180
EV    0.481993
WN    0.447408
B6    0.412941
US    0.395787
9E    0.380457
UA    0.377036
DL    0.335252
AA    0.323081
VX    0.304358
HA    0.272414
AS    0.251506
Name: count, dtype: float64

In [20]:
df_clean.groupby('carrier')['arr_delay'].sum()

carrier
9E     75510.0
AA      -527.0
AS     -6564.0
B6    358576.0
DL     43155.0
EV    508326.0
F9     13549.0
FL     46496.0
HA     -1834.0
MQ    141569.0
OO        80.0
UA    143884.0
US     35376.0
VX     -1582.0
WN    102403.0
YV      5376.0
Name: arr_delay, dtype: float64

In [21]:
df_clean.to_csv("E:\Pós\data/clean_df.csv", index=False)

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\cutie\AppData\Local\Temp\ipykernel_20260\3677403326.py:1: SyntaxWarning: invalid escape sequence '\P'
  df_clean.to_csv("E:\Pós\data/clean_df.csv", index=False)

In [22]:
df_clean = df_clean.copy()


df_clean['route'] = df_clean['origin'] + "-" + df_clean['dest']
df_clean.groupby('route')['arr_delay'].mean().sort_values(ascending=False).head(10)

route
EWR-GSO    212.000000
EWR-CAE     77.857143
EWR-CMH     68.750000
EWR-TYS     52.217391
EWR-OKC     50.020833
JFK-CLE     48.000000
LGA-TVC     47.000000
EWR-TUL     45.147059
EWR-DAY     38.902778
EWR-GSP     36.629870
Name: arr_delay, dtype: float64

In [24]:
df_clean.groupby('route')['arr_delay'].count().sort_values(ascending=False)

route
JFK-LAX    10094
LGA-ATL     9617
LGA-ORD     8395
JFK-SFO     6255
JFK-BOS     5739
           ...
EWR-GSO        1
JFK-STL        1
LGA-AVL        1
LGA-GSO        1
LGA-MYR        1
Name: arr_delay, Length: 217, dtype: int64

In [25]:
df_clean.groupby('tailnum')['arr_delay'].mean().sort_values(ascending=False)

tailnum
N844MH    320.0
N922EV    276.0
N587NW    264.0
N851NW    219.0
N457UW    215.0
          ...
N592AS    -35.5
N915DN    -39.0
N537AS    -40.0
N517AS    -40.5
N560AS    -53.0
Name: arr_delay, Length: 3909, dtype: float64

In [26]:
df_clean.groupby('tailnum')['arr_delay'].count().sort_values(ascending=False)

tailnum
N328AA    342
N327AA    339
N338AA    339
N335AA    332
N258JB    324
         ...
N683BR      1
N32626      1
N26906      1
N978SW      1
N107US      1
Name: arr_delay, Length: 3909, dtype: int64

In [27]:
valid_planes = df_clean['tailnum'].value_counts()
valid_planes = valid_planes[valid_planes >= 50].index

df_filtered_planes = df_clean[df_clean['tailnum'].isin(valid_planes)]

df_filtered_planes.groupby('tailnum')['arr_delay'].mean().sort_values(ascending=False)

tailnum
N11192    32.547945
N15910    30.732919
N989AT    29.500000
N16987    28.643411
N12175    28.452632
            ...
N839VA   -12.042553
N855VA   -13.482759
N852VA   -13.806452
N848VA   -14.324324
N854VA   -16.289855
Name: arr_delay, Length: 1636, dtype: float64